config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
   authenticated :user do
    root "courses#index", as: :authenticated_root
   end

   unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
   end
  end

  root :to => "devise/sessions#new"
  resources :contents
  resources :chapters
  resources :courses
  
  get '/download/:id', to: 'contents#download', as: 'download'
end

app/models/content.rb
class Content < ApplicationRecord  
  include RailsSortable::Model
  
  mount_uploader :content_files, ContentFileUploader  
  belongs_to :chapter  
  set_sortable :cont_order
  
  default_scope { order(cont_order: :asc) }
  
  validates :title, presence: true
  validates_length_of :title, maximum: 255
  
  validates :chapter_id, presence: true
  validates :summernote_content, presence: true, :if => Proc.new { |cont| cont.content_type == 1 }
  validates :content, presence: true, :if => Proc.new { |cont| cont.content_type == 2 }
  validates :content_files, presence: true, :if => Proc.new { |cont| cont.content_type != 1 && cont.content_type != 2 }
  
  validate :audio_valid?, :if => Proc.new { |cont| cont.content_type == 3 && cont.content_files.present? }
  validate :video_valid?, :if => Proc.new { |cont| cont.content_type == 4 && cont.content_files.present? }
  validate :pdf_valid?, :if => Proc.new { |cont| cont.content_type == 5 && cont.content_files.present? }
  
  def audio_valid?
    if content_files.file.content_type != "audio/mp3" && content_files.file.content_type != "audio/wav"
      errors.add(:base, "Attached file must be Audio File and Extension must be mp3 or wav")
    end
  end
  
  def video_valid?
    if content_files.file.content_type != "video/quicktime" && content_files.file.content_type != "video/mp4" && content_files.file.content_type != "video/x-flv" && content_files.file.content_type != "video/x-ms-wmv" && content_files.file.content_type != "video/avi"
      errors.add(:base, "Attached file must be Video File and Extension must be among mov, mp4, flv, wmv or avi")
    end
  end
  
  def pdf_valid?
    if content_files.file.content_type != "application/pdf"
      errors.add(:base, "Attached file must be pdf File and Extension must be pdf")
    end
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    if params[:chapter_id].present?
      @chapter = Chapter.find(params[:chapter_id])
    end
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)
    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update  
    @content = Content.find(params[:id])
    
    if @content.present?
      if @content.summernote_content.present?
        if params[:content][:content].present? || params[:content][:content_files].present?
          params[:content][:summernote_content] = nil
        end
      elsif @content.content.present?
        if params[:content][:summernote_content].present? || params[:content][:content_files].present?
          params[:content][:content] = nil
        end
      elsif @content.content_files.present?
        if params[:content][:summernote_content].present? || params[:content][:content].present?
          params[:content][:content_files] = nil
        end
      end      
    end
    
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def download
    @content = Content.find(params[:id])    
    filepath = @content.content_files.current_path
    stat = File::stat(filepath)
    send_file(filepath, :filename => @content.content_files_identifier, :length => stat.size)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:title, :cont_order, :content, :chapter_id, :created_at, :updated_at, :content_files, :content_type, :summernote_content)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_detail.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <div class="card border-secondary mb-3">
          <div class="card-body text-secondary">
            <div class="col-md-12 mb-3">
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'Edit', edit_content_path(@content), :class => "btn btn-sm btn-outline-warning cus-btn" %>
                  <%= link_to 'Delete', content_path(@content), method: :delete, data: {confirm: "Are you sure you want to delete?"}, :class => "btn btn-sm btn-outline-warning cus-btn" %>
                </div>
              </div>
            </div>
            <label class="col-md-3 control-label">Course:</label>
            <div class="col-md-9 mb-3">
              <%= @content.chapter.course.name %>
            </div>
            <label class="col-md-3 control-label">Chapter:</label>
            <div class="col-md-9 mb-3">
              <%= @content.chapter.title %>
            </div>
            <label class="col-md-3 control-label">Title:</label>
            <div class="col-md-9 mb-3">
              <%= @content.title %>
            </div>
            <% if @content.summernote_content.present? %>
              <label class="col-md-3 control-label">Summernote Content:</label>
              <div class="col-md-9 mb-3">
                <%= @content.summernote_content.html_safe %>
              </div>
            <% end %>
            <% if @content.content.present? %>
              <label class="col-md-3 control-label">Content:</label>
              <div class="col-md-9 mb-3">
                <%= @content.content.html_safe %>
              </div>
            <% end %>
            <% if @content.content_files.present? %>
              <label class="col-md-3 control-label">Downloadable Content: </label>
              <div class="col-md-9 mb-3">
                <%= link_to @content.content_files_identifier, download_path(@content.id), :class => "btn-sm btn-outline-warning cus-btn"  %>
              </div>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contents/_form.html.erb
<div class="row">
  <div class="container col-md-12 cus-margin">
    <div class="card">
      <div class="card-header cus-font">        
        <% if @content.id.present? %>
          Editing Content
        <% else %>
          New Content
        <% end %>
      </div>
      <div class="card-body">
        <%= simple_form_for @content do |f| %>
          <div cliass="col-md-12">
            <% if @content.errors.any? %>
              <div id="error_explanation">
                <ul>
                  <% @content.errors.full_messages.each do |message| %>
                    <li class="font-error"><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          </div>
          <div cliass="col-md-12">
            <div class="form-group">
              <label class="col-md-2 control-label">Title:</label>
              <div class="col-md-10 mb-3">
                <%= f.text_field :title, class: "form-control cus-form-font" %>
              </div>
            </div>                         
              <div class="form-group">
                <label class="col-md-2 control-label">Chapter:</label>
                <div class="col-md-10 mb-3">
                  <% if @chapter.present? %>
                    <%= f.collection_select(:chapter_id, Chapter.all, :id, :title, {include_blank: false, :selected => @chapter.id}, {class: "form-control cus-form-font"}) %>
                  <% else %>
                    <%= f.collection_select(:chapter_id, Chapter.all, :id, :title, {include_blank: false}, {class: "form-control cus-form-font"}) %>
                  <% end %>                  
                </div>
              </div>
            <div class="form-group">
              <label class="col-md-2 control-label">Choose Content Type:</label>
              <div class="col-md-10 mb-3">
                <%= f.select(:content_type, [["A little bit of everything","1"], ["HTML Text","2"], ["Audio","3"], ["Video","4"], ["pdf","5"]], {:selected => @content.content_type}, { :class => 'form-control cus-form-font', :onchange => 'change_content()' }) %>
              </div>
            </div>
            <div id="content-summernote">
              <div class="form-group">
                <label class="col-md-2 control-label">Summernote Content:</label>
                <div class="col-md-10 mb-3">
                  <%= f.input :summernote_content, as: :summernote, label: false %>
                </div>
              </div>
            </div>
            <div id="content-html">
              <div class="form-group">
                <label class="col-md-2 control-label">HTML Text:</label>
                <div class="col-md-10 mb-3">
                  <%= f.text_area :content, class: "form-control cus-form-font", cols: "30", rows: "10" %>
                </div>
              </div>
            </div>
            <div id="content-audio">
              <div class="form-group">
                <label class="col-md-2 control-label">Audio:</label>
                <div class="col-md-10 mb-3">
                  <%= f.file_field :content_files, multiple: false, class: "form-control cus-form-font cus-form-height" %>
                </div>
              </div>
            </div>
            <div id="content-video">
              <div class="form-group">
                <label class="col-md-2 control-label">Video:</label>
                <div class="col-md-10 mb-3">
                  <%= f.file_field :content_files, multiple: false, class: "form-control cus-form-font cus-form-height" %>
                </div>
              </div>
            </div>
            <div id="content-pdf">
              <div class="form-group">
                <label class="col-md-2 control-label">pdf:</label>
                <div class="col-md-10 mb-3">
                  <%= f.file_field :content_files, multiple: false, class: "form-control cus-form-font cus-form-height" %>
                </div>
              </div>
            </div>
            <% if @content.content_files.present? %>
              <div class="form-group">
                <label class="col-md-2 control-label">&nbsp;</label>
                <div class="col-md-10 mb-3">
                  <span style="color: #e6ab67"><%= @content.content_files_identifier %></span>
                </div>
              </div>
            <% end %>
            <div class="form-group">
              <div class="col-md-2 pull-right">
                <%= f.submit "Save", class: "form-control cus-form-font btn btn-warning" %>
              </div>
            </div>
          </div>
          <script>
            $(document).ready(function () {
              change_content();
            });
          </script>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/contents/_list.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="sortable">
        <% @contents.each_with_sortable_id do |content, sortable_id| %>
          <div id="<%= sortable_id %>" class="col-md-6">
            <div class="card border-secondary mb-3 cus-cont-box">
              <div class="card-body text-secondary cus-cont-scroll">
                <div class="col-md-12 mb-3">
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to 'View More', content, :class => "btn btn-sm btn-outline-warning cus-btn" %>
                      <%= link_to 'Edit', edit_content_path(content), :class => "btn btn-sm btn-outline-warning cus-btn" %>
                      <%= link_to 'Delete', content_path(content), method: :delete, data: {confirm: "Are you sure you want to delete?"}, :class => "btn btn-sm btn-outline-warning cus-btn" %>
                    </div>
                  </div>
                </div>
                <label class="col-md-3 control-label">Course:</label>
                <div class="col-md-9 mb-3">
                  <%= content.chapter.course.name %>
                </div>
                <label class="col-md-3 control-label">Chapter:</label>
                <div class="col-md-9 mb-3">
                  <%= content.chapter.title %>
                </div>
                <label class="col-md-3 control-label">Title:</label>
                <div class="col-md-9 mb-3">
                  <%= content.title %>
                </div>
                <% if content.summernote_content.present? %>
                  <label class="col-md-3 control-label">Summernote Content:</label>
                  <div class="col-md-9 mb-3">
                    <%= content.summernote_content.html_safe %>
                  </div>
                <% end %>
                <% if content.content.present? %>
                  <label class="col-md-3 control-label">HTML Text:</label>
                  <div class="col-md-9 mb-3">
                    <%= content.content.html_safe %>
                  </div>
                <% end %>
                <% if content.content_files.present? %>
                  <label class="col-md-3 control-label">Downloadable Content: </label>
                  <div class="col-md-9 mb-3">
                    <%= link_to content.content_files_identifier, download_path(content.id), :class => "btn-sm btn-outline-warning cus-btn"  %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>  
      </div>
    </div>
  </div>
</div>

app/views/contents/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div id="content_form">
    <%= render 'form' %>
  </div>
  </br>
</div>

app/views/contents/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="container col-md-12 cus-margin">
      <div class="card">
        <div class="card-header cus-font">
          Chapters
        </div>
        <div class="card-body">          
          <div class="row">
            <div class="col-md-2">
              <%= link_to 'New Content', new_content_path, class: "form-control cus-form-font btn btn-warning" %>
            </div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-12">
              <% if @contents.present? %>
                <div id="content_list_form">
                  <%= render 'list' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</br>

app/views/contents/new.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div id="content_form">
    <%= render 'form' %>
  </div>
  </br>
</div>

app/views/contents/show.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="container col-md-12 cus-margin">
      <div class="card">
        <div class="card-header cus-font">
          Content Detail
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-12">
              <div id="content_detail">
                <%= render 'detail' %>
              </div>
            </div>
          </div>
          </br>
        </div>
      </div>
    </div>
  </div>
</div>