config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
   authenticated :user do
    root "courses#index", as: :authenticated_root
   end

   unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
   end
  end

  root :to => "devise/sessions#new"
  resources :contents
  resources :chapters
  resources :courses
  
  get '/download/:id', to: 'contents#download', as: 'download'
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  include RailsSortable::Model
  
  belongs_to :course
  has_many :contents, :dependent => :destroy
  
  set_sortable :chap_order
  
  validates :title, presence: true
  validates_length_of :title, maximum: 255
  
  validates :course_id, presence: true
  
  default_scope { order(chap_order: :asc) }
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.order(:chap_order).all
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    if params[:course_id].present?
      @course = Course.find(params[:course_id])
    end
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)
    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:title, :chap_order, :course_id, :created_at, :updated_at, :contents => [:title, :cont_order, :content, :chapter_id, :created_at, :updated_at])
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_content_list.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="sortable">
        <% @chapter.contents.each_with_sortable_id do |content, sortable_id| %>
          <div id="<%= sortable_id %>" class="col-md-6">
            <div class="card border-secondary mb-3 cus-cont-box">
              <div class="card-body text-secondary cus-cont-scroll">
                <%= simple_form_for content do |f| %>
                  <div class="col-md-12 mb-3">
                    <div class="d-flex justify-content-between align-items-center">
                      <label class="col-md-4 control-label">Chapter:</label>
                      <div class="col-md-8 mb-3">
                        <%= f.collection_select(:chapter_id, Chapter.all, :id, :title, {include_blank: false, :selected => @chapter.id}, {class: "form-control cus-form-font"}) %>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12 mb-3">
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <%= f.submit "Change Chapter", class: "btn btn-sm btn-outline-warning cus-btn" %>
                        <%= link_to 'View More', content, :class => "btn btn-sm btn-outline-warning cus-btn" %>
                        <%= link_to 'Edit', edit_content_path(content), :class => "btn btn-sm btn-outline-warning cus-btn" %>
                        <%= link_to 'Delete', content_path(content), method: :delete, data: {confirm: "Are you sure you want to delete?"}, :class => "btn btn-sm btn-outline-warning cus-btn" %>
                      </div>
                    </div>
                  </div>
                  <label class="col-md-3 control-label">Title:</label>
                  <div class="col-md-9 mb-3">
                    <%= content.title %>
                  </div>
                  <% if content.summernote_content.present? %>
                    <label class="col-md-3 control-label">Summernote Content:</label>
                    <div class="col-md-9 mb-3">
                      <%= content.summernote_content.html_safe %>
                    </div>
                  <% end %>
                  <% if content.content.present? %>
                    <label class="col-md-3 control-label">HTML Text:</label>
                    <div class="col-md-9 mb-3">
                      <%= content.content.html_safe %>
                    </div>
                  <% end %>
                  <% if content.content_files.present? %>
                    <label class="col-md-3 control-label">Downloadable Content: </label>
                    <div class="col-md-9 mb-3">
                      <%= link_to content.content_files_identifier, download_path(content.id), :class => "btn-sm btn-outline-warning cus-btn"  %>
                    </div>
                  <% end %>
                <% end %>
                </div>
              </div>
            </div>
          <% end %>
       </div>
    </div>
  </div>
</div>

app/views/chapters/_detail.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <div class="card border-secondary mb-3">
          <div class="card-body text-secondary">
            <div class="col-md-12 mb-3">
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'Edit', edit_chapter_path(@chapter), :class => "btn btn-sm btn-outline-warning cus-btn" %>
                  <%= link_to 'Delete', chapter_path(@chapter), method: :delete, data: {confirm: "Are you sure you want to delete?"}, :class => "btn btn-sm btn-outline-warning cus-btn" %>
                </div>
              </div>
            </div>
            <label class="col-md-3 control-label">Course:</label>
            <div class="col-md-9 mb-3">
              <%= @chapter.course.name %>
            </div>
            <label class="col-md-3 control-label">Title:</label>
            <div class="col-md-9 mb-3">
              <%= @chapter.title %>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chapters/_form.html.erb
<div class="row">
  <div class="container col-md-12 cus-margin">
    <div class="card">
      <div class="card-header cus-font">
        <% if @chapter.id.present? %>
          Editing Chapter
        <% else %>
          New Chapter
        <% end %>
      </div>
      <div class="card-body">
        <%= simple_form_for @chapter do |f| %>
          <% if @chapter.errors.any? %>
            <div id="error_explanation">
              <ul>
                <% @chapter.errors.full_messages.each do |message| %>
                  <li class="font-error"><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div cliass="col-md-12">
            <div class="form-group">
              <label class="col-md-2 control-label">Course:</label>
              <div class="col-md-10 mb-3">
                <% if @course.present? %>
                  <%= f.collection_select(:course_id, Course.all, :id, :name, {include_blank: false, :selected => @course.id}, {class: "form-control cus-form-font"}) %>
                <% else %>
                  <%= f.collection_select(:course_id, Course.all, :id, :name, {include_blank: false}, {class: "form-control cus-form-font"}) %>
                <% end %>
              </div>
            </div>    
            <div class="form-group">
              <label class="col-md-2 control-label">Title:</label>
              <div class="col-md-10 mb-3">
                <%= f.text_field :title, class: "form-control cus-form-font" %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-md-2 pull-right">
                <%= f.submit "Save", class: "form-control cus-form-font btn btn-warning" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/chapters/_list.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="sortable">
        <% @chapters.each_with_sortable_id do |chapter, sortable_id| %>
          <div id="<%= sortable_id %>" class="col-md-6">
            <div class="card border-secondary mb-3 cus-cont-box2">
              <div class="card-body text-secondary cus-cont-scroll">
                <div class="col-md-12 mb-3">
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to 'View More', chapter, :class => "btn btn-sm btn-outline-warning cus-btn" %>
                      <%= link_to 'Edit', edit_chapter_path(chapter), :class => "btn btn-sm btn-outline-warning cus-btn" %>
                      <%= link_to 'Delete', chapter_path(chapter), method: :delete, data: {confirm: "Are you sure you want to delete?"}, :class => "btn btn-sm btn-outline-warning cus-btn" %>
                    </div>
                  </div>
                </div>
                <label class="col-md-3 control-label">Course:</label>
                <div class="col-md-9 mb-3">
                  <%= chapter.course.name %>
                </div>
                <label class="col-md-3 control-label">Title:</label>
                <div class="col-md-9 mb-3">
                  <%= chapter.title %>
                </div>
                </div>
              </div>
            </div>
          <% end %>  
        </div>
       </div>
    </div>
  </div>
</div>

app/views/chapters/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div id="chapter_form">
    <%= render 'form' %>
  </div>
  </br>
</div>

app/views/chapters/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="container col-md-12 cus-margin">
      <div class="card">
        <div class="card-header cus-font">
          Chapters
        </div>
        <div class="card-body">          
          <div class="row">
            <div class="col-md-2">
              <%= link_to 'New Chapter', new_chapter_path, class: "form-control cus-form-font btn btn-warning" %>
            </div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-12">
              <% if @chapters.present? %>
                <div id="chapter_list_form">
                  <%= render 'list' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</br>

app/views/chapters/new.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div id="chapter_form">
    <%= render 'form' %>
  </div>
  </br>
</div>

app/views/chapters/show.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="container col-md-12 cus-margin">
      <div class="card">
        <div class="card-header cus-font">
          Chapter Detail
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-2">
              <%= link_to 'New Content', {:controller => "contents", :action => "new", :chapter_id => @chapter.id }, class: "form-control cus-form-font btn btn-warning" %>
            </div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-12">
              <div id="chapter_detail">
                <%= render 'detail' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </br>
  <div class="row">
    <div class="container col-md-12 cus-margin">
      <div class="card">
        <div class="card-header cus-font">
          Contents
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-12">
              <% if @chapter.contents.present? %>
                <div id="content_list_form">
                  <%= render "content_list" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>