config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
   authenticated :user do
    root "courses#index", as: :authenticated_root
   end

   unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
   end
  end

  root :to => "devise/sessions#new"
  resources :contents
  resources :chapters
  resources :courses
  
  get '/download/:id', to: 'contents#download', as: 'download'
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="pull-right">
      <strong>&copy; 2019 Course Builder Thinkific Hackathon. ALL RIGHTS RESERVED.</strong>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark background-lightblue">
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to courses_path do %>
          <%= image_tag asset_path('thinkific_logo.png'), :class => "style_image" %>
        <% end %>
      </li>
      <li class="nav-item active">
        <h2 class="text-white"></h2>
      </li>
      <li class="nav-item active">
        <h2 class="text-white">Course Builder System</h2>
      </li>
    </ul>
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
	Logged in as <strong><%= current_user.email %></strong>.
	<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      <% else %>
	<%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link' %> |
	<%= link_to 'Login', new_user_session_path, :class => 'navbar-link' %>
      <% end %>
    </p>	
  </div>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto pull-right">
      <li class="nav-item active">
        <%= link_to 'Courses', courses_path, :class => "btn btn-outline-warning cus-btn" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Chapters', chapters_path, :class => "btn btn-outline-warning cus-btn" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contents', contents_path, :class => "btn btn-outline-warning cus-btn" %>
      </li>
    </ul>
  </div>
</nav>
</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseBuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= favicon_link_tag asset_path('course_favicon.png') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom' %>

    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>
    <%= stylesheet_link_tag "#{params[:controller]}/#{params[:action]}" if ::Rails.application.assets.find_asset("#{params[:controller]}/#{params[:action]}.css") %>

    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag "#{params[:controller]}" if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>
    <%= javascript_include_tag "#{params[:controller]}/#{params[:action]}" if ::Rails.application.assets.find_asset("#{params[:controller]}/#{params[:action]}.js") %>

  </head>

  <body>
    <!-- Wrapper-->
    <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">

      <!-- Page wraper -->
      <div id="page-wrapper" class="gray-bg <%= @extra_class %>">

        <!-- Header -->
          <%= render 'layouts/header' %>
        <!-- End Header -->

        <!-- Main view  -->
        <div id="body-content" class="content">
	  <% if notice %>
	    <p class="alert alert-success"><%= notice %></p>
	  <% end %>
	  <% if alert %>
	    <p class="alert alert-danger"><%= alert %></p>
	  <% end %>
          <%=yield %>
        </div>
        <!-- End Main view  -->

        <!-- Footer -->
        <%= render 'layouts/footer' %>
        <!-- End Footer -->

      </div>
      <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->
  </body>
</html>